apiVersion: v1
kind: Pod
metadata:
  name: basic-http
spec:
  volumes:
    - name: "magic-data"
      hostPath:
          path: "/tmp/magic"
  containers:
    - image: bitops/basic-http-pod:0.0.3
      name: basic-http
      volumeMounts:
        - mountPath: "/magic"
          name: "magic-data"
      resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "750m"
            memory: "256Mi"
      livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
      readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
