apiVersion: v1
kind: Pod
metadata:
  name: basic-http
spec:
  containers:
    - image: bitops/basic-http-pod:0.0.1
      name: basic-http
      resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "750m"
            memory: "256Mi"
      livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
      readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
