---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/bitops/kubefarm.git
    branch: master

jobs:
- name: build
  public: true
  plan:
  - get: source-code
    trigger: true
